#!/bin/bash

# RENDER DEPLOY - Quick Start
# Este script mostra os passos essenciais para deployer no Render

echo "╔════════════════════════════════════════════════════════════════════════════╗"
echo "║                      🚀 DEPLOY NO RENDER - GUIA RÁPIDO                     ║"
echo "║                                                                            ║"
echo "║              CRM Vendas Pro - PostgreSQL Edition v2.0.0                    ║"
echo "╚════════════════════════════════════════════════════════════════════════════╝"
echo ""
echo "📋 PASSOS ESSENCIAIS:"
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  PREPARAR CÓDIGO LOCAL"
echo "    ├─ git add ."
echo "    ├─ git commit -m 'PostgreSQL deployment'"
echo "    └─ git push origin main"
echo ""
echo "2️⃣  CRIAR RECURSOS NO RENDER (https://render.com)"
echo "    ├─ Dashboard → New + → PostgreSQL"
echo "    │  └─ Aguardar 2-5 minutos"
echo "    │"
echo "    └─ Dashboard → New + → Web Service"
echo "       ├─ Conectar GitHub"
echo "       ├─ Build: npm install"
echo "       └─ Start: node backend/server.js"
echo ""
echo "3️⃣  ADICIONAR VARIÁVEIS DE AMBIENTE"
echo "    ├─ PORT=10000"
echo "    ├─ HOST=0.0.0.0"
echo "    ├─ NODE_ENV=production"
echo "    ├─ DB_HOST=<seu-db.render.com>"
echo "    ├─ DB_USER=postgres"
echo "    ├─ DB_PASSWORD=<sua-senha>"
echo "    ├─ DB_NAME=crm_vendas_pro"
echo "    ├─ DB_PORT=5432"
echo "    └─ JWT_SECRET=<gere-com-comando-abaixo>"
echo ""
echo "    🔑 Gerar JWT_SECRET:"
echo "    node -e \"console.log(require('crypto').randomBytes(32).toString('hex'))\""
echo ""
echo "4️⃣  DEPLOY"
echo "    ├─ Automático: git push origin main"
echo "    └─ Ou Manual: Dashboard → Manual Deploy"
echo ""
echo "5️⃣  TESTAR"
echo "    ├─ https://seu-servico.onrender.com"
echo "    ├─ Email: admin@crm.local"
echo "    ├─ Senha: JL10@dez"
echo "    └─ ⚠️  Mudar senha após primeiro login!"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "📖 DOCUMENTAÇÃO:"
echo "    ├─ DEPLOY_RENDER.md       → Guia completo"
echo "    ├─ RENDER_CHECKLIST.md    → Checklist passo a passo"
echo "    └─ RENDER_PRODUCAO.md     → Otimizações e segurança"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "✅ CHECKLIST:"
echo "    ☐ Código no GitHub"
echo "    ☐ PostgreSQL criado (aguarde confirmação)"
echo "    ☐ Web Service criado"
echo "    ☐ 9 variáveis de ambiente adicionadas"
echo "    ☐ Deploy completado"
echo "    ☐ Health check OK"
echo "    ☐ Login funciona"
echo "    ☐ Senha admin mudada"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""
echo "🆘 PROBLEMAS?"
echo "    Consulte DEPLOY_RENDER.md seção TROUBLESHOOTING"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
